[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.88sdaws.fun

[redis]
localhost

[user]
user-dev.88sdaws.fun

[cart]
cart-dev.88sdaws.fun

[mysql]
mysql-dev.88sdaws.fun

[shipping]
shipping-dev.88sdaws.fun

[rabbitmq]
rabbitmq-dev.88sdaws.fun

[payment]
payment-dev.88sdaws.fun

[frontend]
frontend-dev.88sdaws.fun






